### ISSUE TITLE
Feature value lost after svm-scale

### ISSUE THREAD

**Issue by Snipx** [cjlin1/libsvm#107]
When using [bug.txt](https://github.com/cjlin1/libsvm/files/1443258/bug.txt) file as the argument for svm-scale (full command is `svm-scale bug.txt > out.txt`), value for feature `16` in object 1326 gets lost. See [out.txt](https://github.com/cjlin1/libsvm/files/1443259/out.txt).

_bug.txt_:

```
...
...13:0 14:0 15:0 16:10 17:0 18:0 19:0 20:0...
...
```

_out.txt_:
```
...
...13:-1 14:-1 15:-1 17:-1 18:-1 19:-1 20:-1...
...
```

Note that the value for feature number 16 is lost.

The bug was reproduced for the latest release version (`3.22`) on Windows binaries, in Java wrapper and by manual making on Linux.

**Comment by cjlin1** [comment]
This isn't a bug because 0 values are not stored

Alexey Subach writes:

**Comment by Snipx** [comment]
Sadly, I haven't found that in the documentation and this was more than unexpected for me. But thanks, @cjlin1. Closing the issue now.
