### ISSUE TITLE
svm save model no c param for RBF

### ISSUE THREAD

**Issue by lukadt** [cjlin1/libsvm#116]
I just train my model with **grid search and cross validation** to get optimal c and gamma params using **c_svm** and **rbf** kernel. Upon saving the **svm to disk** it seems as if **C param is not saved** in **svm_save_model** as when after I call **svm_read_problem** the C params is zero. 
Am i totally missing something or is there a real issue?

https://github.com/cjlin1/libsvm/blob/88a1881f03ca139beff93170d7e6f36477fabe54/svm.cpp#L2647

**Comment by cjlin1** [comment]
This isn't an issue as C isn't used in prediction. Only parameters needed for prediction are stored in the model.
