### ISSUE TITLE
Missing return in csr_scale?

### ISSUE THREAD

**Issue by chengpocheng** [cjlin1/libsvm#123]
When I use csr_scale in python, it's always return None.
I found variable "scaled_x" in commonutil.py, but there is no return in this funciton.
Could I add "return scaled_x" in csr_scale manually?

**Comment by cjlin1** [comment]
Yes, this is a known bug. We will fix it in the next version
You can add that manually

chengpocheng writes:

**Comment by chengpocheng** [comment]
Thank you!

**Comment by chengpocheng** [comment]
Thank you!
