### ISSUE TITLE
Scaling output file format in win10?

### ISSUE THREAD

**Issue by wuxianshen** [cjlin1/libsvm#124]
Thanks for all your contribution which helps me a lot...

I have a question that in my system(win10).
I use svm-scale.exe to scale the data directly like svmguide1, and I get the output file svmguide1.scale, which is in format UTF16-LE, then the file cannot be used as the input of svm-train.exe;
But if I use the easy.py to finish the whole process, things seems to be all right, and the output file svmguide1.scale is in format ANSI;
Can I ask the reason of this difference?
![issue](https://user-images.githubusercontent.com/21985528/45679896-2b2c8480-bb6c-11e8-8a2c-accaead3b64c.png)

**Comment by cjlin1** [comment]
how did you generate things by svm-scale.exe? I used the cmd window to generate a file by svm-scale.exe and can open the file by notepad/wordpad without problem
