### ISSUE TITLE
Typo Error in Matlab's README

### ISSUE THREAD

**Issue by caitaozhan** [cjlin1/libsvm#126]
Typo error location: libsvm/matlab/README, line 218

matlab> [predict_label_P, accuracy_P, dec_values_P] = svmpredict(test_label, [(1:120)', test_data* **train_data**'], model_precomputed);

The **train_data** should be **test_data**?

**Comment by cjlin1** [comment]
train_data is correct because you need to calculate the kernel value 
between test instance and support vectors. Note that this is for the 
precomputed kernel setting.

**Comment by caitaozhan** [comment]
Got it. It seemed weird to me at first. Now I understand. Sorry.
