### ISSUE TITLE
Whether the svdd in libsvm can support negative examples?

### ISSUE THREAD

**Issue by 13952522076** [cjlin1/libsvm#128]
Whether the svdd or one class svm in libsvm can support negative examples?
 
The readme file says "For one-class SVM, label is not used and can be any number".

However, the link "[https://github.com/cjlin1/libsvm/pull/74](https://github.com/cjlin1/libsvm/pull/74) " say "Support for negative examples in one-class added".

So, I am really confused. Thank you very much for your patience and I am looking forward for your reply.

**Comment by cjlin1** [comment]
For oneclass or svdd, the input is not labelled.. So it doesn't matter 
if you indicate the training labels as positive or negative

**Comment by cjlin1** [comment]
No we don't plan to support this

**Comment by 13952522076** [comment]
Thank you very much for your reply. Have a good day ^_^
