### ISSUE TITLE
One-class classification examples

### ISSUE THREAD

**Issue by human098** [cjlin1/libsvm#130]
Hi, sorry if this is the wrong place to post. Very new to SVM, was wondering if there were any examples of a one-class classifier (ie. trained on normal data, tested on normal and novel data) using LibSVM in Java. Is the only thing we need to set to make it a one-class classifier "param.svm_type    = svm_parameter.ONE_CLASS;"? 

Also, are there any tools to make one-class classification selection of parameters easier? (Similar to easy.py for what I'm assuming is multi-class or binary classification). Thank you.

**Comment by cjlin1** [comment]
Please check README. If you write a java code to call libsvm, besides svm_type you also need to choose some parameters such as nu, kernel, kernel parameters etc.
