### ISSUE TITLE
Wrong values in range file generated by svm-scale

### ISSUE THREAD

**Issue by Xinyao90** [cjlin1/libsvm#133]
I use svm-scale to scale my input so that each feature has range in [0,1] and the parameters are stored in file rang3rd. However, the minimum value of the third feature is wrong since the values of the third feature are all positive but the minimum value is negative. 

The command I used: svm-scale -l 0 -u 1 -s range3rd train3rd.data > train3rd.scale
Here is the content in range3rd file, the 3rd feature's min negative value is in bold:
x
0 1
1 626564 792386
2 216271 277056
3 **-4293791624** 2042181
4 64541 82353
5 5585 13492
6 524523 1020279
7 0 11 

[TrainingData&RangeFile.zip](https://github.com/cjlin1/libsvm/files/2789507/TrainingData.RangeFile.zip)

**Comment by cjlin1** [comment]
It does have negative values:

$ cut -f 4 -d ' ' train3rd.data | cut -c 3-|sort -n
-4293791624
-4293789819
-4293777007
...
2028513
2041403
2042181



Xinyao90 writes:
