### ISSUE TITLE
E2285 Could not find a match for 'max<T>(int,long)'

### ISSUE THREAD

**Issue by blaisexen** [cjlin1/libsvm#135]
**svm.cpp** during build time,
int max_iter = max(10000000, l>INT_MAX/100 ? INT_MAX : 100*l);
//int max_iter = INT_MAX; //**ready to change like this**????

E2285 Could not find a match for 'max<T>(int,long)'

I also get this issue from **svm-train.c**,
			case 'q':
				svm_set_print_string_function = &print_null; //Lvalue required????
                                //svm_set_print_string_function; //**ready to change like this**????
				i--;
				break;

Did I mess anything aside from compiling or building, I used 2.89 before now upgrade to 3.23 but error comes out.  Any help?

**Comment by cjlin1** [comment]
I suspect this is related to the version of visual C/C++ you used? Do 
you know the version number?

**Comment by blaisexen** [comment]
hi,
I'm sorry I did not specify which version I used, or I'm using Embarcadero C++Builder 10.2.2

Lately LibSVM 2.89 has no problem, and now I used 3.23(latest update)?

from svm.cpp I just used this 
`int max_iter = INT_MAX;`

I don't know what's the advantage using the exact or default Max<T>iteration

from svm.h,
```
case 'q':
svm_set_print_string_function;
i--;
break;
```
Do you think that's fine?

**Comment by cjlin1** [comment]
On 2019-02-23 08:14, blaisexen wrote:
> hi,
> I'm sorry I did not specify which version I used, or I'm using
> Embarcadero C++Builder 10.2.2
> 
> Lately LibSVM 2.89 has no problem, and now I used 3.23(latest update)?
> 
> 
> from svm.cpp I just used this
> int max_iter = INT_MAX;
> 

using this is fine as the max #iter is very rarely  reached.

> I don't know what's the advantage using the exact or default
> Maxiteration
> 
> from svm.h,
> 
> case 'q':
> svm_set_print_string_function;
> i--;
> break;
> 

Should be ok unless you really want -q to remove all outputs.

**Comment by blaisexen** [comment]
thank you
