### ISSUE TITLE
[TYPO] 'labal' instead of 'label'

### ISSUE THREAD

**Issue by miguelangel** [cjlin1/libsvm#138]
Hi,

When reading the **README** file, I have noticed that one of the paragraphs contains the word 'labal', instead of 'label'.

Please find below the paragraph I am referring to:

> Each line contains an instance and is ended by a '\n' character. For
> \<labal> in the training set, we have the following cases.

Hope it helps.

Regards,
Miguel

**Comment by cjlin1** [comment]
Thanks and handled. You will see the fix in the next release

**Comment by miguelangel** [comment]
Hi @cjlin1 ,

It looks like fixed now. Thank you!
