### ISSUE TITLE
the svmpredict is seem to not work well

### ISSUE THREAD

**Issue by haiwenheaven** [cjlin1/libsvm#141]
after compile the test with hearscale is work but when i test my dataset the svmpredict is not work that always rreturn empty accuracy

**Comment by cjlin1** [comment]
Could you provide more details?

**Comment by haiwenheaven** [comment]
@cjlin1 when i train a model and predict like "model = svmtrain(train_wine_labels, train_wine, '-c 2 -g 1');   [predict_label, accuracy] = svmpredict(test_wine_labels, test_wine, model);
  i get a empty accuracy

**Comment by cjlin1** [comment]
how about predict_label?
and what is the screen output of svmpredict

**Comment by haiwenheaven** [comment]
@cjlin1 sorry,maybe i will reply to you in some days ,beacause at first i want to sovle this problem by installing matlab agian  but now i .make another trouble in installing matlab
