### ISSUE TITLE
Question: SVDD code compatible with LIBSVM 3.23?

### ISSUE THREAD

**Issue by stpr-unb** [cjlin1/libsvm#147]
Based on the [link on your website](https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/#libsvm_for_svdd_and_finding_the_smallest_sphere_containing_all_data), I am planning to conduct some experiments using SVDD. The website links LIBSVM 3.22, however looking at the commit messages for LIBSVM3.23, it appears to me that it is only fixing python code and not any of the code use to compile the MEX file, so I suspect that I should be able to use it without issues. Am I correct to assume this?

**Comment by cjlin1** [comment]
Yes I think so

**Comment by stpr-unb** [comment]
Thank you, I think the mex compilted successfully and initial tests appear to be working. I will close this issue.
