### ISSUE TITLE
Error while installing on Mac

### ISSUE THREAD

**Issue by nipungupta98** [cjlin1/libsvm#154]
I am using mac OS Mojave 10.14.6. When I `make` it encounters following error among others:
```
In file included from svm.cpp:1:
/Library/Developer/CommandLineTools/usr/include/c++/v1/math.h:761:41: error: no
      member named 'fabsf' in the global namespace
abs(float __lcpp_x) _NOEXCEPT {return ::fabsf(__lcpp_x);}
```

Other errors are similar to this one and are related to math.h. I have updated xcode but nothing helped.
Thanks!

**Comment by cjlin1** [comment]
This is an issue not related to libsvm.. It's related to the 
commandlinetools on mac. Check for example

https://github.com/PointCloudLibrary/pcl/issues/2601

**Comment by nipungupta98** [comment]
Thanks!
