### ISSUE TITLE
Confuse about “dual variables constraint" of OneClassSVM

### ISSUE THREAD

**Issue by TsaiYunLin** [cjlin1/libsvm#157]
Hi, I read the paper "Estimating the Support of a High-Dimensional Distribution" about one-class-svm which provided on the webpage.

I noticed that the dual variables have a constraint that ∑_i α_i =1.

But when I tried to use and call clf._dual_coef_ **(interface implemented by sklearn which directed to dual variables of libsvm)**, I found that the sum of the dual variables would not be 1.

Did I miss any detail about it?

Thanks

**Comment by cjlin1** [comment]
libsvm scales the dual problem of one-class svm. See eq 8 of
https://www.csie.ntu.edu.tw/~cjlin/papers/libsvm.pdf

**Comment by TsaiYunLin** [comment]
Thank you so much.
