### ISSUE TITLE
Fixing a random seed with srand() does not work on ubuntu 18.04

### ISSUE THREAD

**Issue by franklevasseur** [cjlin1/libsvm#171]
Hi there,

I recently wanted to seed Libsvm with a random seed. I followed the directions mentionned [here](https://www.csie.ntu.edu.tw/~cjlin/libsvm/faq.html#f503) and called `srand()` function right before calling `svm_train()`.

So my code basically looks like this:

```
srand(42);
svm_model *model = svm_train(state->problem, &params);
```
**This works fine on Windows**, but on Ubuntu, I get varying results... Here's an example of the model after calling train with the exact same parameters and dataset twice in a row:

![libsvm_rand](https://user-images.githubusercontent.com/25970722/86152800-b4f1db80-bace-11ea-8396-adb77c3f28ea.png)

Also, I use datasets with `l < 200`. So its not that big.

Should I try different random number generators? If so, I can fork this repo and change only the calls to `rand()`...

Am I missing something?

Thank you in advance for any help,

François

**Comment by franklevasseur** [comment]
I replaced all usage of `rand` and `srand` by `std::mt19937` of package `<random>` and it solved all my problems.

François

**Comment by cjlin1** [comment]
Please see the following faq:
https://www.csie.ntu.edu.tw/~cjlin/libsvm/faq.html#f503

Q: On some systems CV accuracy is the same in several runs. How could I
use different data partitions? In other words, how do I set random seed
in LIBSVM?

If you use GNU C library, the default seed 1 is considered. Thus you
always get the same result of running svm-train -v. To have different
seeds, you can add the following code in svm-train.c:

#include <time.h>

and in the beginning of main(),

srand(time(0));

Alternatively, if you are not using GNU C library and would like to use
a fixed seed, you can have

srand(1);

For Java, the random number generator is initialized using the time
information. So results of two CV runs are different. To fix the seed,
after version 3.1 (released in mid 2011), you can add

svm.rand.setSeed(0);

in the main() function of svm_train.java.

If you use CV to select parameters, it is recommended to use identical
folds under different parameters. In this case, you can consider fixing
the seed.

**Comment by franklevasseur** [comment]
@cjlin1 

Yeah I know! That's exactly the first thing I tried...

Still, I don't know why, `rand()` was producing different results on two different runs with the same seed (`srand(42)`)...

I forked your repo and solved my problem [here](https://github.com/botpress/libsvm).

Now that I use `std::mt19937`, I not only have consistent results on Linux Ubuntu, but I also have consistent results accross plateforms (Windows 10).

You should check it out.

François
