### ISSUE TITLE
ArrayOutOfBoundException in java v3.2

### ISSUE THREAD

**Issue by TKlerx** [cjlin1/libsvm#18]
I have encountered an ArrayOutOfBoundException in version 3.2, that does not exist in v2.8.
Here is the stacktrace:
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at libsvm.Cache.get_data(svm.java:63)
	at libsvm.ONE_CLASS_Q.get_Q(svm.java:1208)
	at libsvm.Solver.Solve(svm.java:496)
	at libsvm.svm.solve_one_class(svm.java:1422)
	at libsvm.svm.svm_train_one(svm.java:1516)
	at libsvm.svm.svm_train(svm.java:1959)
	at LibSvmBug.svmTrain(LibSvmBug.java:95)
	at LibSvmBug.train(LibSvmBug.java:59)
	at LibSvmBug.main(LibSvmBug.java:38)

In v2.8 the output is the following:
*
optimization finished, #iter = 0
obj = NaN, rho = Infinity
nSV = 246, nBSV = 245

I made a sample class. Run bug.sh and working.sh which can be found here:
https://www.dropbox.com/s/gnx9a9n1293spz4/LibSvmBug.tar.gz?dl=0

With version 2.8 you will get no exception, but with version 3.2 you will get an ArrayOutOfBoundException
(Please do not care about the strange parameter choices)

I also tested some other versions. The bug also occurs in v. 2.81, 2.88, 2.91, 3.00, 

Edit: Running java version "1.7.0_65"
OpenJDK Runtime Environment (IcedTea 2.5.3) (7u71-2.5.3-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)
(Same exception on Oracle VM on Ubuntu)

Just verified this on Windows 8 using jre7 and starting from eclipse.

**Comment by cjlin1** [comment]
we now see that this problem occurs if some extreme parameters are used and then the resulting G is not a valid floating-point number in the subroutine for working set selection. Changes on c and java code will appear in the next release
