### ISSUE TITLE
Importing scikit-learn SVM model to LIBSVM

### ISSUE THREAD

**Issue by Afef00** [cjlin1/libsvm#184]
Hello,
I have trained my SVM model for MNIST classification in Python using scikit-learn( Grid searchcv). I need to implement the SVM prediction in C language using the model parameters extracted in Python. I was wondering is there any way to import the trained model to LIBSVM ? Is it possible to use the model parameters (from python) in svm-predict of LIBSVM?
Regards,

**Comment by cjlin1** [comment]
You can check sources of libsvm python interface about the python model 
structure

**Comment by rotkiv1205** [comment]
I'm also curious about this and didn't get the answer? 😄

**Comment by cjlin1** [comment]
What's the structure of the output model of GridSearchCV? If this model is different from the one produced by libsvm, then it's not possible to directly call libsvm for prediction. I think the easiest way is that after GridSearch returns the best configureation, re-train the SVM model by libsvm python interface.
