### ISSUE TITLE
v330 changes the serialization format in Java

### ISSUE THREAD

**Issue by Craigacp** [cjlin1/libsvm#187]
`svm_model` instances saved in versions using `java.io.Serializable` before v330 can't be loaded into v330. The addition of the `double[] prob_density_marks` field changed the implicit serialVersionUID from `278220065587415279` to `7290957281464828818` and so deserializing old models using the new code throws `InvalidClassException`.

There isn't really an easy way around this problem, it might be possible to do by specifying a `readObject` method on the `svm_model` class, but I couldn't find any good examples of doing so. Specifying the `serialVersionUID` to one value or the other will prevent this from occurring again, but at the cost of preventing models with the other value from loading.

**Comment by cjlin1** [comment]
Sorry for the late reply.. Sorry for the troubles caused by v330 release. I don't see what we can easily do on our side. Is it possible that you just re-train your model? Thanks

**Comment by Craigacp** [comment]
There isn't much that can be done now, but fixing the serialVersionUID to `7290957281464828818` by adding the field `static final long serialVersionUID = 7290957281464828818L` to the `svm_model` class will prevent it from happening again if the model format changes. We've decided not to upgrade to v330 until the next major version of our library where we've moved off `java.io.Serializable` and have a work around due to that because we can't break existing users.
