### ISSUE TITLE
PyPi package confusion

### ISSUE THREAD

**Issue by naetherm** [cjlin1/libsvm#189]
Are there any plans in regards to www.pypi.org claiming ownership over the module name `libsvm` which is maintained by @ocampor ?
In our group this lead to some confusion that the official source is available under `libsvm-official` and not under `libsvm` as one would suspect.

**Comment by cjlin1** [comment]
Thanks for asking. We contained the maintainer sometime ago. But due to the different designs of his and ours, we now have the libsvm-official
