### ISSUE TITLE
How to use the saved trained svm model file  manually

### ISSUE THREAD

**Issue by ha-daiy** [cjlin1/libsvm#196]
I have trained a svm model ( for instance with these configs : svm_type: c_svc
                                                                                                               kernel_type: rbf
                                                                                                               gamma: 0.076923076923076927
                                                                                                               nr_class: 2
                                                                                                               total_sv : 132
                                                                                                               rho: 0.42446205176771579
                                                                                                               label: 1 -1
                                                                                                               nr_sv: 64 68)
**I am wondering if there could be a way to use the saved trained model model file manually to make prediction for the test data.**
The training and test data samples are as follows:
2 samples of Training/Test data:
+1 1:0.708333 2:1 3:1 4:-0.320755 5:-0.105023 6:-1 7:1 8:-0.419847 9:-1 10:-0.225806 12:1 13:-1 
-1 1:0.583333 2:-1 3:0.333333 4:-0.603774 5:1 6:-1 7:1 8:0.358779 9:-1 10:-0.483871 12:-1 13:1 

It will be of great pleasure if you could help.

**Comment by cjlin1** [comment]
You can do that by following what svm_predict_values() in svm.cpp did. The issue is that you need a program to do kernel evaluations..
