### ISSUE TITLE
why my memory always 

### ISSUE THREAD

**Issue by xiaotaofeng** [cjlin1/libsvm#198]
my conditions: linear kernel ; six features; Binary classification（good or bad）
my question: when my points reach to 15000（good）and 15000（bad）；at this time its training，the Memory is increasing all the time，and then Memory crash，my PC memory is 8G

**Comment by cjlin1** [comment]
For libevm, it stores kernel elements. That's why your memory is not enough. If you use liblinear,  it does not store kernel values so you won't get memory problems
