### ISSUE TITLE
gridregression.py 出现  RuntimeError: get no mse

### ISSUE THREAD

**Issue by alymer1** [cjlin1/libsvm#203]
林老师好，在用svm-train.exe做回归时，使用gridregression.py最优化参数c，g过程中，输入命令为：

           Microsoft Windows [版本 6.1.7601]
           版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

           C:\Users\skxy>d:

           D:\>cd d:\zhuanmen

           d:\zhuanmen>Python gridregression.py  -svm-train d:\zhuanmen\svm-train.exe - gnu
           plot d:\zhuanmen\gnuplot\bin\gnuplot.exe –log2c -10,10,1 –log2g -10,10,1 –log
           2p -10,10,1 –v 10 -s 3 –t 2 d:\zhuanmen\heart_scale.txt

结果出现：
                  
           Traceback (most recent call last):
              File "gridregression.py", line 274, in run
                if mse is None: raise RuntimeError('get no mse')
           RuntimeError: get no mse
           worker local quit.

因担心本人数据文件存在格式等问题，使用heart_scale.txt做检验，结果仍然出现上述问题，请林老师帮助看问题可能出现在哪些环节，谢谢。

本人对gridregression.py 文件里self.svmtrain_pathname、# svmtrain_pathname、self.gnuplot_pathname行的路径做了修改，修改后如下：

class GridOption:
	def __init__(self, dataset_pathname, options):
		dirname = os.path.dirname(__file__)
		if sys.platform != 'win32':
			self.svmtrain_pathname = os.path.join(dirname, '../svm-train')
			self.gnuplot_pathname = '/usr/bin/gnuplot'
		else:
			# example for windows
			self.svmtrain_pathname = os.path.join(dirname, r'd:\zhuanmen\svm-train.exe')
			# svmtrain_pathname = r'd:\zhuanmen\svm-train.exe'
			self.gnuplot_pathname = r'd:\zhuanmen\gnuplot\bin\gnuplot.exe'

使用计算机是windows7，    64位操作系统。

**Comment by cjlin1** [comment]
I think the reason is that you wrongly have "- gnuplot" instead of 
"-gnuplot"
BTW, gnuplot isn't used for gridregression so you don't even need to 
specify -gnuplot

**Comment by alymer1** [comment]
林老师好,感谢为我解答疑难。我目前主要是想使用svm-train.exe做回归(regression)，涉及到一个参数优化的环节，尤其是参数c，g，您能给出一个办法吗？
