### ISSUE TITLE
使用svm-train.exe做回归(regression)，参数c与g如何优化

### ISSUE THREAD

**Issue by alymer1** [cjlin1/libsvm#205]
林老师好,感谢为我解答疑难。我目前主要是想使用svm-train.exe做回归(regression)，涉及到一个参数优化的环节，尤其是参数c，g，您能给出一个办法吗？

**Comment by cjlin1** [comment]
Did you check "Grid Parameter Search for Regression" at https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/#grid_parameter_search_for_regression ??
