### ISSUE TITLE
Questions about probability estimation of one-class svm

### ISSUE THREAD

**Issue by KarenMars** [cjlin1/libsvm#210]
Hi,

I have some questions related to the implementation of the probability estimation of the one-class svm:

-  The first question is how to calculate the probability estimation when the number of positive or negative predictions is smaller than 5. I found that the probability estimation will not be calculated in this situation. Does it mean that the model can only generate the decision values rather than the probabilities?  Why do we manually generate some predicted decision values in the positive area or the negative area to enable the probability estimation?

- The second question is when there are many decision values in the same value, the decision value of this value can be mapped into different intervals. Is it reasonable?

**Comment by cjlin1** [comment]
For the 1st, yes, we don't give probabilities if # data is too small.

For the 2nd, we agree that it's a problem. May you give us your data and 
settings so we can see if a better way can be done

**Comment by GoXian** [comment]
Why do we manually generate some predicted decision values in the positive area or the negative area to enable the probability estimation?

**Comment by cjlin1** [comment]
Please see details in the following paper
https://www.csie.ntu.edu.tw/~cjlin/papers/oneclass_prob/oneclass_prob.pdf

**Comment by GoXian** [comment]
> 详情请见以下纸 https://www.csie.ntu.edu.tw/~cjlin/papers/oneclass_prob/oneclass_prob.pdf

Thanks.
