### ISSUE TITLE
如何调整nu，使训练集的准确率增加？

### ISSUE THREAD

**Issue by GoXian** [cjlin1/libsvm#211]

**Comment by GoXian** [comment]
你好我发现对比nu为0.1、0.2、0.3、0.4、0.5，训练集的准确率会逐渐减小。但是当我想要训练集准确率更加大时，将nu设置成 0.05 甚至更小也没有什么变化。

**Comment by GoXian** [comment]
你好，
我发现对比nu为0.1、0.2、0.3、0.4、0.5，训练集的准确率会逐渐减小。但是当我想要训练集准确率更加大时，将nu设置成 0.05 甚至更小也没有什么变化。

**Comment by cjlin1** [comment]
So looks like you would like to fit data for getting higher training accuracy? You cannot just lower nu to achieve that. You also need to adjust the kernel parameter gamma of the Gaussian kernel.

**Comment by GoXian** [comment]
> 所以看起来你想拟合数据以获得更高的训练准确性？你不能仅仅降低 nu 来实现这一目标。您还需要调整高斯核的核参数 gamma。

感谢您的回复，请问你有什么针对 OCSVM 的 RBF 核函数进行调整 nu 和 gamma 的方法吗？
目前我使用的是较小的nu值，gamma值从大到小逐渐遍历（幸运的是我数据量很小），直到在 CrossValidation 中训练集达到了一定的准确率时，就得到了gamma值。想听听您的意见。

**Comment by cjlin1** [comment]
You mentioned one-class SVM, which is unsupervised. For your training data, do you have labels? If so, why not using standard two-class SVM?

**Comment by GoXian** [comment]
> You mentioned one-class SVM, which is unsupervised. For your training data, do you have labels? If so, why not using standard two-class SVM?

因为我的训练样本是全都是正样本，没有负样本，所以没有使用 two-class SVM。
