### ISSUE TITLE
 cannot find -lgcc: No such file or directory

### ISSUE THREAD

**Issue by KOUKILEO** [cjlin1/libsvm#212]
I have a problem when compiling LIBSVM. I cannot make. What is the problem?
OS= Ubuntu 22.04.3
![image](https://github.com/cjlin1/libsvm/assets/20551345/d1fde09b-68ae-45ab-948d-3378ee8a7fca)

**Comment by cjlin1** [comment]
I think this is due to that your gcc was not properly installed. It's not related to libsvm. You can to see if your gcc can be used to compile any simple C programs
