### ISSUE TITLE
When using svm-scale , missing values come out.

### ISSUE THREAD

**Issue by Endlesswinds** [cjlin1/libsvm#213]
The original dataset had no missing values, but once I used svm-scale , the result consists of donzons of missing values. Why?

**Comment by cjlin1** [comment]
Please see the following libsvm faq:

Q: Why sometimes not all attributes of a data appear in the
training/model files ?

libsvm uses the so called "sparse" format where zero values do
not need to be stored. Hence a data with attributes

1 0 2 0

is represented as

1:1 3:2
