### ISSUE TITLE
MATLAB Crashes when trying to run "svmtrain" on CentOS

### ISSUE THREAD

**Issue by tk27182** [cjlin1/libsvm#215]
I'm trying to run some feature selection and classification models using libsvm-3.17 on my university's supercomputer. I haven't had issues in the past running these functions and libsvm-3.17 has been properly made on my system. But recently, the code will start running and then crash once it tries to use "svmtrain". It generates the attached segment violation and crash dump. I've tried re-compiling libsvm, running on a different cluster, increasing memory, but I still get this report. I reached out to MATLAB support and based on what they read in the crash report, there may be a bug in the C/C++ code. I've attached the error report here.

Is this a known issue with CentOS or Rocky8?

[matlab_error_report.txt](https://github.com/cjlin1/libsvm/files/15193493/matlab_error_report.txt)

**Comment by cjlin1** [comment]
We need more information. Can you give us your whole code?

**Comment by tk27182** [comment]
I'm sorry, this was user error. It works fine.
