### ISSUE TITLE
Checking for users before running program

### ISSUE THREAD

**Issue by ljos** [cjlin1/libsvm#22]
Hi again,

I am using the lab machines at my university, but I don't want to inconvenience others if they are sitting there. I had some problems implementing that with your grid.py, but I discovered that I could reimplement most of the functionality (that I needed) through gnu parallel instead. 

```bash
#!/usr/bin/env bash

LOGFILE=$(mktemp "XXXX.parallel.log")

function unused {
    parallel --plain                                                \
             --sshloginfile ..                                      \
             --nonall                                               \
             --tag                                                  \
             '[[ -z $(users | sed "s/$USER//") ]] && echo "unused"' \
        | sed -e 's/\s*unused//'                                    \
              -e 's/^/4\//'
}

function exit_parallel {
    parallel --plain                                \
             --sshloginfile ..                      \
             --nonall                               \
             'killall -q -u $USER svm-train'
    rm "$LOGFILE"
}

trap 'echo "Ctrl-C detected.";                  \
          exit_parallel;                        \
          exit 130'                             \
     SIGINT SIGQUIT

parallel --plain                                    \
         --sshloginfile <(unused)                   \
         --filter-hosts                             \
         --joblog "$LOGFILE"                        \
         --resume-failed                            \
         --timeout 28800                            \
         --tag                                      \
         'nice svm-train -q                         \
                         -m 1024                    \
                         -h 0                       \
                         -v 5                       \
                         -c $(echo 2^{1} | bc -l)   \
                         -g $(echo 2^{2} | bc -l)   \
                 "'$DATA'"                          \
              | sed -e "s/Cross .* = //"            \
                    -e "s/%//"'                     \
         ::: {-5..15..2}                            \
         ::: {3..-15..-2}
```

This does make some assumptions according to my environment (like the home folder always being the same on every machine). You also need to configure the script directly in the script. I just thought I would tell you as you might be interested in it (or someone else following this repository).

**Comment by cjlin1** [comment]
Sorry for the late reply. This is certainly interesting.
One main feature that grid.py provides but not here is
that grid.py randomly sample (c,g) points. So even if you do not
finish all points, a rough contour can be obtained.
Given the principle that libsvm support one functionality by
only one way, I don't think we will include your code.
However, if you agree, we can add an faq item about this
alternative way of doing grid. Please let us know what
you think

Chih-Jen


Bjarte Johansen writes:

**Comment by ljos** [comment]
> On 15 Jan 2015, at 07:55, cjlin1 <notifications@github.com> wrote:
> 
> Sorry for the late reply.
No problem. 

> One main feature that grid.py provides but not here is 
> that grid.py randomly sample (c,g) points. So even if you do not 
> finish all points, a rough contour can be obtained. 
Are you sure you are randomly sampling? How I read the code it certainly is a different order than what I do, but I can’t find a single call to random when you do the ordering of the points. I don’t completely understand the ordering code, though.

The reason I didn’t do it the way you do it is that I have enough machines so that I can run (almost) all of the tests in parallel at once. The biggest problem is that some of them take a long time to complete and I can’t hog the machines forever. With this in mind I didn’t see the need for any ordering of the points. It is, however, something I could easily fix if someone found it useful.

You also have the incremental gnuplot stuff. I have been thinking about how to do that, but I haven’t decided for a good way to do that.

> Given the principle that libsvm support one functionality by 
> only one way, I don't think we will include your code.
I didn’t expect you to, I just thought you might find it interesting so I sent it your way :D

> However, if you agree, we can add an faq item about this 
> alternative way of doing grid. Please let us know what 
> you think 

I have no problem with that. I have added the code to a repo here: https://github.com/ljos/svm-grid <https://github.com/ljos/svm-grid> 
This way if anyone else finds it interesting or needs something done with it they can contact me.

Regards,
Bjarte

**Comment by cjlin1** [comment]
Bjarte Johansen writes:
 > > On 15 Jan 2015, at 07:55, cjlin1 <notifications@github.com> wrote:
 > >
 > > Sorry for the late reply.
 > No problem.
 > 
 > > One main feature that grid.py provides but not here is
 > > that grid.py randomly sample (c,g) points. So even if you do not
 > > finish all points, a rough contour can be obtained.
 > Are you sure you are randomly sampling? How I read the code it certainly is a
 > different order than what I do, but I can’t find a single call to random when you
 > do the ordering of the points. I don’t completely understand the ordering code,
 > though.
 > 
 > The reason I didn’t do it the way you do it is that I have enough machines so
 > that I can run (almost) all of the tests in parallel at once. The biggest problem
 > is that some of them take a long time to complete and I can’t hog the machines
 > forever. With this in mind I didn’t see the need for any ordering of the points.
 > It is, however, something I could easily fix if someone found it useful.
 >

Yes, see
	def permute_sequence(seq):
in grid.py
 > You also have the incremental gnuplot stuff. I have been thinking about how to do
 > that, but I haven’t decided for a good way to do that.
 > 
 > > Given the principle that libsvm support one functionality by
 > > only one way, I don't think we will include your code.
 > I didn’t expect you to, I just thought you might find it interesting so I sent it
 > your way :D
 > 
 > > However, if you agree, we can add an faq item about this
 > > alternative way of doing grid. Please let us know what
 > > you think
 > 
 > I have no problem with that. I have added the code to a repo here: https://
 > github.com/ljos/svm-grid <https://github.com/ljos/svm-grid>
 > This way if anyone else finds it interesting or needs something done with it they
 > can contact me.
 >

Just added an faq with link. Thank you so much for the work
Chih-jen

**Comment by ljos** [comment]
I have been looking at `permute_sequence` and it does change the order, but I don't understand why it does it in the way it does:
```py
permute_sequence([1,2,3,4,5,6,7,8,9])
#  => [5, 3, 8, 2, 7, 4, 9, 1, 6]
```
This function will always give the same output for the same input, and I don't see why this sequence is better than another one. If I had done this and wanted a random order I would just have used
[`random.shuffle`](https://docs.python.org/2/library/random.html#random.shuffle) instead.

**Comment by cjlin1** [comment]
Yes, we don't do just random shuffling. We try to generate a "coarse"
grid first and keep refine it. That's the reason of generating such
a sequence
Chih-Jen

Bjarte Johansen writes:

**Comment by ljos** [comment]
Oh, so the point is to do it in such a sequence so you get a outline of the contour? I think you said that earlier, but it didn't click before now.

**Comment by cjlin1** [comment]
Bjarte Johansen writes:
 > Oh, so the point is to do it in such a sequence so you get a outline of the
 > contour? I think you said that earlier, but it didn't click before now.
 >

Yes.
