### ISSUE TITLE
API stability in releases

### ISSUE THREAD

**Issue by bkpoon** [cjlin1/libsvm#222]
I help manage the `libsvm` conda package on the [conda-forge channel](https://anaconda.org/conda-forge/libsvm). Does `libsvm` follow semantic versioning (https://en.wikipedia.org/wiki/Software_versioning#Semantic_versioning, https://semver.org) where API changes are only in the "major" version number (i.e. "3") and not in the "minor" version number (i.e. "35")? If so, we can add some additional information for conda to use when trying to create compatible environments. A PR to add that information is at https://github.com/conda-forge/libsvm-feedstock/pull/36

Thanks!

**Comment by tan5166** [comment]
Yeap, you're basically right.
