### ISSUE TITLE
Correctness of array indexing in file "svm.cpp"

### ISSUE THREAD

**Issue by ayv19** [cjlin1/libsvm#226]
File svm.cpp. The index i could be -1:
Line 826:   if(i != -1) // NULL Q_i not accessed: Gmax=-INF if i=-1

Is it correct to access an array element with a negative index?:
Line 841:   double quad_coef = QD[i]+QD[j]-2.0*y[i]*Q_i[j];

**Comment by cjlin1** [comment]
Thank you for the comment. If i=-1, it means Gmax = -INF. In this
situation, quad_diff = -INF (or Nan if G[j] is some IEEE special quantity)
Then grad_diff > 0 is never true. Therefore, Q_i is not accessed.

We can do a return statement when i=-1.. But somehow we hope return occurs only in the end.
An if statement is possible, but the code is slightly uglier.
