### ISSUE TITLE
Using LIBSVM with OpenMP under Octave

### ISSUE THREAD

**Issue by kvantas** [cjlin1/libsvm#27]
Hello,
I don't have enough development experience on Linux, forgive me if I ask something obvious.

1. I added the -fopenmp to CFLAGS and -lgomp to MEX_OPTION at /matlab/Makefile
2. I added to /Makefile -fopenmp to CFLAGS
3. In svm.cpp I added:
   3.1 "#pragma omp parallel for private(j)" above the line "for(j=start;j<len;j++)"  (1285 line)
   3.2  "#pragma omp parallel for private(i) reduction(+:sum)" above the line "for(i=0;i<model->l;i++)" (2511 line)
   3.3  #pragma omp parallel for private(i)" above the line "for(i=0;i<l;i++)"  (2528 line)
4. I run under octave the make command

Then when I am using the svmtrain under Octave I get the  error: /home/Octave/libsvm_mp/matlab/svmtrain.mex: failed to load: /home/Octave/libsvm_mp/matlab/svmtrain.mex: undefined symbol: omp_get_thread_num

What am I doing wrong here?

(Ubuntu 14.04, Octace 3.8.1, gcc 4.9, libsvm 3.20 )

**Comment by cjlin1** [comment]
We have improved the description in libsvm faq. Please check

Thanks,
Chih-Jen

Konstantinos Vantas writes:

**Comment by mricherzhagen** [comment]
Kind of offtopic, but since you mention the FAQ:

> Not Found
>
> The requested URL /~cjlin/libsvm was not found on this server.

When trying to access http://www.csie.ntu.edu.tw/~cjlin/libsvm/
Did the FAQ and webpage move?

**Comment by kvantas** [comment]
Thanks!
Konstantinos

**Comment by cjlin1** [comment]
I can access it.. Don't know what happened to you?

Matthias Richerzhagen writes:
