### ISSUE TITLE
pred_label is not corresponding to pre[pred_label,accuracy,prob_estimates]=svmpredict(test_label,test_data,model,'-b 1');

### ISSUE THREAD

**Issue by tjusxh** [cjlin1/libsvm#51]
In pred_estimates, the position of  the maximum value in one row is not the pred_label. 

prob_estimates=0.0877046072932294	0.00689885694870784	0.0510358500866629	0.0349193526856883	0.0201649925974930	0.0572772003038145	0.00354058458641571	0.434801642194089	0.299917382939861	0.00373953036403846
0.0569029578292815	0.0128889675010719	0.0226503273265042	0.235434067349005	0.0274432928060539	0.0223993134855364	0.00449010998588290	0.372552666098744	0.240135267815857	0.00510302980206350
0.0202618302729419	0.00609933422466536	0.00513096031248623	0.556599397170814	0.00770208398129837	0.0147579801297493	0.00117991662750405	0.123657362841668	0.263114176688193	0.00149695775068038
0.0138081408458132	0.0134109236889526	0.0261085782234978	0.379193740840643	0.0136879003688169	0.0278073190536115	0.00393368980397517	0.0770472704849993	0.441814426316247	0.00318801037344396
0.00737713942130312	0.00719604777712997	0.0190913916210304	0.766244252381808	0.00452925052833849	0.00832667922291313	0.000954117402067928	0.0242901169949015	0.160638180981833	0.00135282366867416
0.0404892166770354	0.0131597503809068	0.00812199404116744	0.0709609923235642	0.0256930503037581	0.0235279018153220	0.00310139828330843	0.190031347957460	0.620513527363689	0.00440082085378811
0.0233835236239888	0.00845191161599723	0.0204935753653564	0.0455692904676819	0.0733235759739852	0.0506628894366520	0.00506885299370543	0.0616635058140948	0.707636494571399	0.00374638013713891
0.0170375648555056	0.0117320006702165	0.0351611195497132	0.0329173319877270	0.0199963414010635	0.0233994742806957	0.00202927477235737	0.0367208285826699	0.809862937232914	0.0111431266671378
0.00249398437648049	0.00118775906267820	0.00420318445065694	0.00150617919781232	0.00851998127528923	0.0170565271724271	0.000216428383816490	0.00376026537283618	0.959633934361137	0.00142175634686587
0.0172952090357666	0.00203085205048888	0.0663402503175806	0.00337260286616463	0.0192039462603744	0.0368582111255392	0.00135917901052383	0.0574097352946263	0.753632624031509	0.0424973900074269
0.000537446336879699	2.15124069324038e-05	0.00561621351527447	0.00185702285684450	8.83922926914827e-05	0.000224499754837717	3.52901270154285e-05	7.98180192575826e-06	0.00140238264873741	0.990209258258861
0.00800564331385912	0.000723560253424673	0.00910529583487216	0.0517704592247967	0.00127130082212482	0.000836563684457387	0.0318391492343732	0.00144605301838154	0.00150543142470253	0.893496543189008
0.00597297494217007	0.00213978859351707	0.0254911330116816	0.0667699924629301	0.00264826602958697	0.00124512773832485	0.0281686476611874	0.00111821134747100	0.00185613966496867	0.864589718548163
0.737566350619235	0.00377211871885958	4.93077713563539e-05	0.00382722305898168	0.000840960416034537	7.15881072403622e-05	0.000763927380789079	0.000475734513815691	0.000236976483126986	0.252395812930561
0.485882559427058	0.179818235887341	0.00491168109845924	0.0735388345615359	0.0108076830998238	0.00347030734890046	0.00671528385336261	0.0153990089988476	0.00948964326287568	0.209966762461795
 
pred_label=6
6
4
9
4
9
9
9
9
9
8
8
8
7
7

**Comment by cjlin1** [comment]
From libsvm/matlab/README

Note that the order of classes here is the same as 'Label' field
in the model structure.




tjusxh writes:

**Comment by tjusxh** [comment]
@cjlin1  Thank you very much. I am not careful.
