### ISSUE TITLE
Calling multiclass_probability when mapping of decision values of binary classifier to probabilities

### ISSUE THREAD

**Issue by yosipk** [cjlin1/libsvm#60]
Hi,

I've got problem with mapping of decision values to probabilities of binary classifier (nr_class = 2). 

In that case in function svm_predict_probability in [L2615 in svm.cpp](https://github.com/cjlin1/libsvm/blob/master/svm.cpp#L2615) multiclass_probability will be called, which implements the method from [this paper](https://www.csie.ntu.edu.tw/~cjlin/papers/svmprob/svmprob.pdf), and the resulting predicted probabilities (let's call them probs1) will not be the same as one just pulled the decision values through sigmoid, what one gets just by calling sigmoid_predict on decision values (let's call these probs2). Both probs1 and probs2 are probability estimates, but they are not the same, and probs2 was directly calibrated to output probabilities, so it makes more sense to output these as probability estimates for binary classifier.

Is there any reason to call multiclass_probability even when the classifier is binary (nr_class = 2)?

Thanks!

**Comment by cjlin1** [comment]
When nr_class = 2, the result after calling multiclass_prob remains the same as that from sigmoid_predict
