### ISSUE TITLE
Java libsvm "reaching max number of iterations", libsvm.dll is not

### ISSUE THREAD

**Issue by idlesysman** [cjlin1/libsvm#62]
Same data,c_type,parameters,the Java  libsvm will  "reaching max number of iterations",but libsvm.dll is not.
Version: 3.21
OS:Win 7 x64
Data:https://github.com/idlesysman/java/blob/master/file/trainData.zip
-------------------------------------------------------------------------------------
Parameters:
param.svm_type = svm_parameter.C_SVC;
param.kernel_type = svm_parameter.RBF;
param.gamma = 0.36; 
param.C = 10;
svm_cross_validation.nr_fold=10
-------------------------------------------------------------------------------------
Using default values:
param.degree = 3;
param.coef0 = 0;
param.nu = 0.5;
param.cache_size = 100;
param.eps = 1e-3;
param.p = 0.1;
param.shrinking = 1;
param.probability = 0;
param.nr_weight = 0;
param.weight_label = new int[0];
param.weight = new double[0];
-------------------------------------------------------------------------------------

thanks!

**Comment by cjlin1** [comment]
You are doing 10-fold CV so the different random splits
of data may cause
different numbers of iters.

Goberl writes:

**Comment by idlesysman** [comment]
tks！
