### ISSUE TITLE
Check parameter failure on not applicable case

### ISSUE THREAD

**Issue by fmigneault** [cjlin1/libsvm#84]
Using the following parameters:

```    
    svm_parameter param;
    param.C = 100;
    param.svm_type = C_SVC;
    param.kernel_type = LINEAR;
    param.eps = 0.00001;
    param.probability = 0;
    param.shrinking = 0;
    param.cache_size = 100;
```    

I ran `svm_check_parameter` to validate and it returned `"degree of polynomial kernel < 0"`.
Since only `POLY` employs `degree`, the parameter's if-condition should also check for kernel type.
A similar issue could be applicable for `gamma` check just above. 

['svm_check_parameter' problematic lines](https://github.com/cjlin1/libsvm/blob/88a1881f03ca139beff93170d7e6f36477fabe54/svm.cpp#L3068-L3072)

The error can obviously be avoided by setting these parameters to zero, making them pass the conditions, but we shouldn't rely simply on this default value. 
Adding a kernel / svm type check where these parameters are employed could avoid a few head scratches for future users of libsvm.

As proof, it just happened to me that `gamma < 0` didn't raise any error while `degree < 0` did.

**Comment by cjlin1** [comment]
Thanks for the suggestion. We did consider this before but didn't do that. Anyway I have done the change as you suggested. It will appear in the next release
