### ISSUE TITLE
No tie-breaking in one-vs-one

### ISSUE THREAD

**Issue by amueller** [cjlin1/libsvm#85]
The prediction from one-vs-one is done here:
https://github.com/cjlin1/libsvm/blob/master/svm.cpp#L2565

And there is no tie-breaking, and in case of a tie, it always predicts 0.
I'm not sure if there is a standard tie-breaking mechanism, but deterministically predicting 0 seems like an odd choice. Is there something I'm missing?

**Comment by cjlin1** [comment]
See the 2nd last paragraph of	Sec 7 in libsvm paper
Andreas Mueller writes:

**Comment by amueller** [comment]
Have you thought about this further?
This doesn't seem to be an edge case to me, for example for three classes.

**Comment by amueller** [comment]
Also thank you for your quick reply!

**Comment by cjlin1** [comment]
we can consider decision values. However, so far we haven't found real cases where ties occur too often. So the implementation for handling this may not be cost-effective
Andreas Mueller writes:
